server:
  port: 8082

spring :
  application :
    name : IDENTITY-PROVIDER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/identity-provider-db
    username: postgres
    password: admin


eureka :
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone : http://localhost:8761/eureka/
    instance :
      hostname : localhost