---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  wedoogiftgateway:
    build: ./wedoogift-gateway
    container_name: wedoogiftGateway
    ports:
      - "8083:8080"



  wedoogiftregistry:
    build: ./registry-service
    container_name: wedoogiftRegistry
    ports:
      - "8761:8080"


  identityprovider:
    build: ./identity-provider-service
    container_name: identityProvider
    ports:
      - "8082:8080"
    depends_on:
      - broker
    environment:
      DEPOSIT_KAFKA_TOPIC: 'deposit.operation'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'


  deposit:
    build: ./deposit-management-service
    container_name: deposit
    depends_on:
      - broker
    ports:
      - "8081:8080"
    environment:
      DEPOSIT_KAFKA_TOPIC: 'deposit.operation'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'



  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: identity-provider-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: unless-stopped


  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret