version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: identity-provider-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: unless-stopped





