server:
  port: 8083

spring :
  application :
    name : WEDOOGIFT-GATEWAY
  cloud:
    gateway:
      routes:
        - id : deposit-service
          uri: lb://DEPOSIT-SERVICE
          predicates :
            - Path=/deposit/**

        - id: identity-provider-service
          uri: lb://IDENTITY-PROVIDER-SERVICE
          predicates:
            - Path=/api/**

eureka :
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone : http://localhost:8761/eureka/
    instance :
      hostname : localhost
